import Head from 'next/head';
import styles from '../styles/Home.module.css';
import LikeButton from '../components/LikeButton';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Like Button</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <LikeButton />
    </div>
  );
}
